name: Build Docker image

on:
  workflow_dispatch:
    inputs:
      version:
        description: application version to apply (e.g. 1.0.2-post5)
        required: true

jobs:
  build-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          build-args: |
            BASE_VERSION=v2.0.4
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ inputs.version }}
          platforms: linux/amd64,linux/arm64
          provenance: false
          push: true

      - name: Write to summary
        run: |
          echo "### Image pushed :ship:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "ghcr.io/${{ github.repository }}:${{ inputs.version }}" >> $GITHUB_STEP_SUMMARY
